version: '3.3'

services:
  auth.api:
    image: safe_shop/identity.api:${TAG:-latest}
    build:
      context: .
    dockerfile: src/Services/Identity/Identity.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - API_URL=http://0.0.0.0:80
      - PATH_BASE=/catalog
  catalog.api:
    image: safe_shop/catalog.api:${TAG:-latest}
    build:
      context: .
    dockerfile: src/Services/Catalog/Catalog.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - API_URL=http://0.0.0.0:80
      - MONGO_CONNECTION=mongodb://127.0.0.1:27017
      - PATH_BASE=/catalog
  shopping.apigw:
    image: safe_shop/shopping.apigw:${TAG:-latest}
    build:
      context: .
      dockerfile: src/ApiGateways/Web.Bff.Shopping/apigw/Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - auth.api
      - catalog.api
