version: '3.3'

services:
  auth.api:
    image: safe_shop/identity.api:${TAG:-latest}
    build:
      context: .
    dockerfile: src/Services/Identity/Identity.Api/Dockerfile
    ports:
      - "5001:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - API_URL=http://0.0.0.0:80
  catalog.api:
    image: safe_shop/catalog.api:${TAG:-latest}
    build:
      context: .
    dockerfile: src/Services/Catalog/Catalog.Api/Dockerfile
    ports:
      - "5002:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - API_URL=http://0.0.0.0:80
      - MONGO_CONNECTION=mongodb://127.0.0.1:27017
